const oldTestamentBooks = [
    // {"name": "gen", "chapters": 50},
    // {"name": "ex", "chapters": 40},
    // {"name": "lev", "chapters": 27},
    // {"name": "num", "chapters": 36},
    // {"name": "deut", "chapters": 34},
    // {"name": "josh", "chapters": 24},
    // {"name": "judg", "chapters": 21},
    // {"name": "ruth", "chapters": 4},
    // {"name": "1-sam", "chapters": 31},
    // {"name": "2-sam", "chapters": 24},
    // {"name": "1-kgs", "chapters": 22},
    // {"name": "2-kgs", "chapters": 25},
    // {"name": "1-chr", "chapters": 29},
    // {"name": "2-chr", "chapters": 36},
    // {"name": "ezra", "chapters": 10},
    // {"name": "neh", "chapters": 13},
    // {"name": "esth", "chapters": 10},
    // {"name": "job", "chapters": 42},
    // {"name": "ps", "chapters": 150},
    // {"name": "prov", "chapters": 31},
    // {"name": "eccl", "chapters": 12},
    // {"name": "song", "chapters": 8},
    // {"name": "isa", "chapters": 66},
    // {"name": "jer", "chapters": 52},
    // {"name": "lam", "chapters": 5},
    // {"name": "ezek", "chapters": 48},
    // {"name": "dan", "chapters": 12},
    // {"name": "hosea", "chapters": 14},
    // {"name": "joel", "chapters": 3},
    // {"name": "amos", "chapters": 9},
    // {"name": "obad", "chapters": 1},
    // {"name": "jonah", "chapters": 4},
    {"name": "micah", "chapters": 7},
    {"name": "nahum", "chapters": 3},
    {"name": "hab", "chapters": 3},
    {"name": "zeph", "chapters": 3},
    {"name": "hag", "chapters": 2},
    {"name": "zech", "chapters": 14},
    {"name": "mal", "chapters": 4}
];

module.exports = oldTestamentBooks;